name: CD - Deploy Docker images (no push)
on:
  push:
    branches:
      - feature/**
      - main


concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  detect-changes:
    name: Detect changed services
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.filter.outputs.changes }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            cal-comp-proc:
              - 'cal-comp-proc/**'
            test-comp-proc:
              - 'test-comp-proc/**'

  build:
    name: Build Docker images (no push)
    needs: [detect-changes]
    runs-on: ubuntu-latest
    if: needs.detect-changes.outputs.services != '[]'
    strategy:
      matrix:
        service: ${{ fromJSON(needs.detect-changes.outputs.services) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./${{ matrix.service }}
          push: false   # 👈 don’t push anywhere
          tags: ${{ matrix.service }}:localtest
