name: CI - Precommit & Tests
on:
  push:
    branches:
      - feature/**
      - main


concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  precommit:
    name: Run pre-commit checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run pre-commit
        run: pre-commit run --all-files

  detect-changes:
    name: Detect changed sources
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: actions/checkout@v3

      - id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            cal-comp-proc:
              - 'cal-comp-proc/**'
            test-comp-proc:
              - 'test-comp-proc/**'
            source-comp-proc:
              - 'source-comp-proc/**'

  pytest:
    name: Run tests on changed sources
    needs: [detect-changes]
    runs-on: ubuntu-latest
    if: needs.detect-changes.outputs.services != '[]'
    strategy:
      matrix:
        service: ${{ fromJSON(needs.detect-changes.outputs.services) }}
    steps:
      - uses: actions/checkout@v3

      - name: Debug - show all changed services
        run: echo "Changed services - ${{ needs.detect-changes.outputs.services }}"

      - name: Debug - show current service in matrix
        run: echo "Running pytest for service - ${{ matrix.service }}"
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install uv
        run: pip install uv

      - name: Install deps & run pytest
        run: |
          cd ${{ matrix.service }}
          uv sync
          uv run pytest
