name: Send Email via Gmail

on:
  workflow_dispatch:

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
      - name: Debug secrets
        run: |
          if [ -z "${{ secrets.SMTP_USERNAME }}" ]; then
            echo "SMTP_USERNAME is empty"
          else
            echo "SMTP_USERNAME loaded"
          fi
          
      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          secure: false
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}

          subject: GitHub Action Test Email
          to: ${{ secrets.SMTP_USERNAME }}
          from: ${{ secrets.SMTP_USERNAME }}

          body: |
            Hello, Good Afternoon!
            You have been provided with read access for this dataset - <>
            You can now query this table using the query

            select * from table;
            
            Regards
            Naanthaan
