name: Send Email via Gmail

on:
  workflow_dispatch:

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          secure: false
          username: vasanthguru75@gmail.com
          password: cccxllgcwxixcgqj

          subject: GitHub Action Test Email
          to: vasanthguru75@gmail.com
          from: vasanthguru75@gmail.com

          body: |
            Hello,

            This email was sent from GitHub Actions.

            Example Query:
            SELECT *
            FROM `project.dataset.table`
            LIMIT 10;

            Regards
            Data Engineering
